---
sidebar: sidebar 
permalink: concepts/choose-class-and-size.html 
keywords: service level, storage class, storage classes, pv size, persistent volume size, volume size, bandwidth, performance, persistent, volume, kubernetes, containers 
summary: O Astra Control Center é compatível com classes de storage Trident com o respaldo de classes de storage ONTAP Storage ou Astra Data Store. Você deve entender como a classe de storage e o tamanho do volume persistente podem ajudar você a atingir seus objetivos de performance. 
---
= Classes de armazenamento e tamanho de volume persistente
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
O Astra Control Center é compatível com o ONTAP ou o Astra Data Store como back-end de storage.



== Visão geral

O Astra Control Center é compatível com o seguinte:

* *Classes de storage do Trident com suporte do armazenamento de dados Astra*: Se você instalou um ou mais clusters de armazenamento de dados Astra manualmente, o Astra Control Center oferece a capacidade de importar e recuperar a topologia (nós, discos), bem como vários status.
+
O Astra Control Center exibe o cluster subjacente do Kubernetes na configuração Astra Data Store, na nuvem à qual o cluster Kubernetes pertence, em quaisquer volumes persistentes provisionados pelo Astra Data Store, no nome do volume interno correspondente, na aplicação que usa o volume persistente e no cluster que contém a aplicação.

* *Classes de storage Trident com suporte do ONTAP storage*: Se você estiver usando um back-end do ONTAP, o Astra Control Center oferece a capacidade de importar o back-end do ONTAP para relatar várias informações de monitoramento.



NOTE: As classes de storage do Trident devem ser pré-configuradas fora do Centro de Controle Astra.



== Classes de armazenamento

Quando você adiciona um cluster ao Astra Control Center, será solicitado que você selecione uma classe de storage configurada anteriormente nesse cluster como a classe de storage padrão. Essa classe de armazenamento será usada quando nenhuma classe de armazenamento for especificada em uma reivindicação de volume persistente (PVC). A classe de armazenamento padrão pode ser alterada a qualquer momento no Astra Control Center e qualquer classe de armazenamento pode ser usada a qualquer momento especificando o nome da classe de armazenamento dentro do gráfico PVC ou Helm. Certifique-se de que você tenha apenas uma única classe de storage padrão definida para o cluster do Kubernetes.

Quando você usa o Astra Control Center integrado a um back-end de storage Astra Data Store, após a instalação, nenhuma classe de storage será definida. Você precisará criar a classe de storage padrão do Trident e aplicá-la ao back-end de storage. Consulte https://docs.netapp.com/us-en/astra-data-store/get-started/setup-ads.html#set-up-astra-data-store-as-storage-backend["Primeiros passos do Astra Data Store"] para criar uma classe de storage padrão do Astra Data Store.



== Para mais informações

* https://docs.netapp.com/us-en/trident/index.html["Documentação do Astra Trident"^]

