---
sidebar: sidebar 
permalink: get-started/install_acc.html 
keywords: astra installation, install astra control center, how to install astra control, deploy, download from netapp support 
summary: Para instalar o Astra Control Center depois de abordar alguns pré-requisitos ambientais, você fará o download do pacote e a instalação seguindo as etapas descritas. 
---
= Instale o Astra Control Center usando o processo padrão
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Para instalar o Centro de Controle Astra, baixe o pacote de instalação no site de suporte da NetApp e execute as etapas a seguir para instalar o Operador do Centro de Controle Astra e o Centro de Controle Astra em seu ambiente. Você pode usar este procedimento para instalar o Astra Control Center em ambientes conetados à Internet ou com conexão via rede.

Para ambientes Red Hat OpenShift, você pode usar um link:../get-started/acc_operatorhub_install.html["procedimento alternativo"] para instalar o Astra Control Center usando o OpenShift OperatorHub.

.O que você vai precisar
* link:requirements.html["Antes de começar a instalação, prepare seu ambiente para a implantação do Astra Control Center"].
* Se você configurou ou deseja configurar políticas de segurança de pod no seu ambiente, familiarize-se com as políticas de segurança de pod e como elas afetam a instalação do Astra Control Center. link:understand-psp-restrictions.html["Compreender as restrições da política de segurança do pod"]Consulte .
* Certifique-se de que todos os operadores de cluster estão em um estado saudável e disponíveis.
+
[source, sh]
----
kubectl get clusteroperators
----
* Certifique-se de que todos os serviços de API estão em um estado saudável e disponíveis:
+
[source, sh]
----
kubectl get apiservices
----
* Certifique-se de que o Astra FQDN que pretende utilizar está roteável para este cluster. Isso significa que você tem uma entrada DNS no seu servidor DNS interno ou está usando uma rota URL principal que já está registrada.
* Se um cert-manager já existir no cluster, você precisará executar alguns link:../get-started/cert-manager-prereqs.html["etapas de pré-requisito"] para que o Astra Control Center não instale seu próprio cert-manager.


.Sobre esta tarefa
O processo de instalação do Astra Control Center faz o seguinte:

* Instala os componentes do Astra no `netapp-acc` namespace (ou nome personalizado).
* Cria uma conta padrão.
* Estabelece um endereço de e-mail de usuário administrativo padrão e uma senha única padrão. Este usuário é atribuído a função proprietário no sistema que é necessário para o login pela primeira vez na IU.
* Ajuda você a determinar que todos os pods do Astra Control Center estão em execução.
* Instala a IU do Astra.



IMPORTANT: (Aplica-se apenas à versão EAP (Astra Data Store Early Access Program)) se você pretende gerenciar o Astra Data Store usando o Astra Control Center e habilitar workflows da VMware, implante o Astra Control Center somente no `pcloud` namespace e não no `netapp-acc` namespace ou namespace personalizado descrito nas etapas deste procedimento.


IMPORTANT: Não execute o seguinte comando durante todo o processo de instalação para evitar a exclusão de todos os pods do Astra Control Center: `kubectl delete -f astra_control_center_operator_deploy.yaml`


NOTE: Se você estiver usando o Podman do Red Hat em vez do Docker Engine, os comandos Podman podem ser usados no lugar dos comandos Docker.

.Passos
Para instalar o Astra Control Center, siga estas etapas:

* <<Faça o download e descompacte o pacote Astra Control Center>>
* <<Instale o plug-in NetApp Astra kubectl>>
* <<Adicione as imagens ao seu registo local>>
* <<Configure namespace e segredo para Registros com requisitos de autenticação>>
* <<Instale o operador do Centro de Controle Astra>>
* <<Configurar o Astra Control Center>>
* <<Instalação completa do operador e do Centro de Controle Astra>>
* <<Verifique o status do sistema>>
* <<Configure a entrada para o balanceamento de carga>>
* <<Faça login na IU do Astra Control Center>>




== Faça o download e descompacte o pacote Astra Control Center

. Faça o download do pacote Astra Control Center (`astra-control-center-[version].tar.gz`) no https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["Site de suporte da NetApp"^].
. Faça o download do zip dos certificados e chaves do Astra Control Center no https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["Site de suporte da NetApp"^].
. (Opcional) Use o seguinte comando para verificar a assinatura do pacote:
+
[source, sh]
----
openssl dgst -sha256 -verify AstraControlCenter-public.pub -signature astra-control-center-[version].tar.gz.sig astra-control-center-[version].tar.gz
----
. Extraia as imagens:
+
[source, sh]
----
tar -vxzf astra-control-center-[version].tar.gz
----




== Instale o plug-in NetApp Astra kubectl

O plug-in da linha de comando NetApp Astra `kubectl` economiza tempo ao executar tarefas comuns associadas à implantação e atualização do Astra Control Center.

.O que você vai precisar
O NetApp fornece binários para o plugin para diferentes arquiteturas de CPU e sistemas operacionais. Você precisa saber qual CPU e sistema operacional você tem antes de executar esta tarefa. Em sistemas operacionais Linux e Mac, você pode usar o `uname -a` comando para coletar essas informações.

.Passos
. Liste os binários de plug-in disponíveis do NetApp Astra `kubectl` e observe o nome do arquivo que você precisa para o seu sistema operacional e arquitetura de CPU:
+
[source, sh]
----
ls kubectl-astra/
----
. Copie o arquivo para o mesmo local que o utilitário padrão `kubectl`. Neste exemplo, o `kubectl` utilitário está localizado no `/usr/local/bin` diretório. Substitua `<binary-name>` pelo nome do arquivo que você precisa:
+
[source, sh]
----
cp kubectl-astra/<binary-name> /usr/local/bin/kubectl-astra
----




== Adicione as imagens ao seu registo local

. Complete a sequência de passos adequada para o seu motor de contentores:


[role="tabbed-block"]
====
.Docker
--
. Mude para o diretório Astra:
+
[source, sh]
----
cd acc
----
. [[substep_image_local_registry_push]]empurre as imagens do pacote no diretório de imagens do Astra Control Center para o seu Registro local. Faça as seguintes substituições antes de executar o comando:
+
** Substitua BUNDLE_FILE pelo nome do arquivo de pacote Astra Control (por exemplo, `acc.manifest.yaml` ).
** Substitua my_REGISTRY pela URL do repositório Docker.
** Substitua my_REGISTRY_USER pelo nome de usuário.
** Substitua my_REGISTRY_TOKEN por um token autorizado para o Registro.
+
[source, sh]
----
kubectl astra packages push-images -m BUNDLE_FILE -r MY_REGISTRY -u MY_REGISTRY_USER -p MY_REGISTRY_TOKEN
----




--
.Podman
--
. Inicie sessão no seu registo:
+
[source, sh]
----
podman login [your_registry_path]
----
. Execute o script a seguir, fazendo a substituição do <YOUR_REGISTRY> conforme observado nos comentários:
+
[source, sh]
----
# You need to be at the root of the tarball.
# You should see these files to confirm correct location:
#   acc.manifest.yaml
#   acc/

# Replace <YOUR_REGISTRY> with your own registry (e.g registry.customer.com or registry.customer.com/testing, etc..)
export REGISTRY=<YOUR_REGISTRY>
export PACKAGENAME=acc
export PACKAGEVERSION=22.08.1-26
export DIRECTORYNAME=acc
for astraImageFile in $(ls ${DIRECTORYNAME}/images/*.tar) ; do
  # Load to local cache
  astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image(s): //')

  # Remove path and keep imageName.
  astraImageNoPath=$(echo ${astraImage} | sed 's:.*/::')

  # Tag with local image repo.
  podman tag ${astraImage} ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}

  # Push to the local repo.
  podman push ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
done
----


--
====


== Configure namespace e segredo para Registros com requisitos de autenticação

. Exporte o KUBECONFIG para o cluster host do Astra Control Center:
+
[source, sh]
----
export KUBECONFIG=[file path]
----
. Se você usar um Registro que requer autenticação, você precisará fazer o seguinte:
+
.. Crie o `netapp-acc-operator` namespace:
+
[source, sh]
----
kubectl create ns netapp-acc-operator
----
+
Resposta:

+
[listing]
----
namespace/netapp-acc-operator created
----
.. Crie um segredo para o `netapp-acc-operator` namespace. Adicione informações do Docker e execute o seguinte comando:
+

NOTE: O marcador de posição `your_registry_path` deve corresponder à localização das imagens que carregou anteriormente (por exemplo, `[Registry_URL]/netapp/astra/astracc/22.08.1-26` ).

+
[source, sh]
----
kubectl create secret docker-registry astra-registry-cred -n netapp-acc-operator --docker-server=[your_registry_path] --docker-username=[username] --docker-password=[token]
----
+
Resposta da amostra:

+
[listing]
----
secret/astra-registry-cred created
----
+

NOTE: Se você excluir o namespace depois que o segredo é gerado, você precisa regenerar o segredo para o namespace depois que o namespace é recriado.

.. Crie o `netapp-acc` namespace (ou nome personalizado).
+
[source, sh]
----
kubectl create ns [netapp-acc or custom namespace]
----
+
Resposta da amostra:

+
[listing]
----
namespace/netapp-acc created
----
.. Crie um segredo para o `netapp-acc` namespace (ou nome personalizado). Adicione informações do Docker e execute o seguinte comando:
+
[source, sh]
----
kubectl create secret docker-registry astra-registry-cred -n [netapp-acc or custom namespace] --docker-server=[your_registry_path] --docker-username=[username] --docker-password=[token]
----
+
Resposta

+
[listing]
----
secret/astra-registry-cred created
----
.. [[substep_kubeconfig_secret]](Opcional) se você quiser que o cluster seja gerenciado automaticamente pelo Astra Control Center após a instalação, certifique-se de fornecer o kubeconfig como um segredo dentro do namespace Astra Control Center que você pretende implantar usando este comando:
+
[source, sh]
----
kubectl create secret generic [acc-kubeconfig-cred or custom secret name] --from-file=<path-to-your-kubeconfig> -n [netapp-acc or custom namespace]
----






== Instale o operador do Centro de Controle Astra

. Altere o diretório:
+
[source, sh]
----
cd manifests
----
. Edite a implantação do operador Astra Control Center YAML ) (`astra_control_center_operator_deploy.yaml`para consultar o Registro local e o segredo.
+
[source, sh]
----
vim astra_control_center_operator_deploy.yaml
----
+

NOTE: Uma amostra anotada YAML segue estes passos.

+
.. Se você usar um Registro que requer autenticação, substitua a linha padrão de `imagePullSecrets: []` pelo seguinte:
+
[source, sh]
----
imagePullSecrets:
- name: <astra-registry-cred>
----
.. Altere `[your_registry_path]` para a `kube-rbac-proxy` imagem para o caminho do registo onde as imagens foram empurradas para um <<substep_image_local_registry_push,passo anterior>>.
.. Altere `[your_registry_path]` para a `acc-operator-controller-manager` imagem para o caminho do registo onde as imagens foram empurradas para um <<substep_image_local_registry_push,passo anterior>>.
.. (Para instalações que usam a pré-visualização do Astra Data Store) consulte este problema conhecido relacionado https://docs.netapp.com/us-en/astra-data-store-2112/release-notes/known-issues.html#mongodb-deployment-with-default-liveness-probe-value-fails-with-pods-in-crash-loop["Provisionadores de classe de storage e alterações adicionais que você precisará fazer no YAML"^]ao .
+
[listing, subs="+quotes"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        *image: [your_registry_path]/kube-rbac-proxy:v4.8.0*
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        *image: [your_registry_path]/acc-operator:[version x.y.z]*
        imagePullPolicy: IfNotPresent
      *imagePullSecrets: []*
----


. Instale o operador do Centro de Controle Astra:
+
[source, sh]
----
kubectl apply -f astra_control_center_operator_deploy.yaml
----
+
Resposta da amostra:

+
[listing]
----
namespace/netapp-acc-operator created
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io created
role.rbac.authorization.k8s.io/acc-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding created
configmap/acc-operator-manager-config created
service/acc-operator-controller-manager-metrics-service created
deployment.apps/acc-operator-controller-manager created
----
. Verifique se os pods estão em execução:
+
[source, sh]
----
kubectl get pods -n netapp-acc-operator
----




== Configurar o Astra Control Center

. Edite o arquivo de recursos personalizados do Astra Control Center (CR) (`astra_control_center_min.yaml`) para criar contas, AutoSupport, Registro e outras configurações necessárias:
+

NOTE: `astra_control_center_min.yaml` É o CR padrão e é adequado para a maioria das instalações. Familiarize-se com tudo link:../get-started/acc_cluster_cr_options.html["Opções de CR e seus valores potenciais"] para garantir que você implante o Astra Control Center corretamente para seu ambiente. Se forem necessárias personalizações adicionais para o seu ambiente, pode utilizar `astra_control_center.yaml` como CR alternativo.

+
[source, sh]
----
vim astra_control_center_min.yaml
----
+

IMPORTANT: Se você estiver usando um Registro que não requer autorização, você deve excluir a  `secret` linha dentro `imageRegistry` ou a instalação falhará.

+
.. Mude `[your_registry_path]` para o caminho do registo onde empurrou as imagens no passo anterior.
.. Altere a `accountName` cadeia de carateres para o nome que deseja associar à conta.
.. Altere a `astraAddress` cadeia de carateres para o FQDN que deseja usar no navegador para acessar o Astra. Não use `http://` ou `https://` no endereço. Copie este FQDN para uso em um <<Faça login na IU do Astra Control Center,passo posterior>>.
.. Altere a `email` cadeia de carateres para o endereço de administrador inicial padrão. Copie este endereço de e-mail para uso em um <<Faça login na IU do Astra Control Center,passo posterior>>.
.. Alterar `enrolled` para AutoSupport para `false` sites sem conetividade com a Internet ou manter `true` para sites conetados.
.. Se você usar um cert-manager externo, adicione as seguintes linhas ao `spec`:
+
[source, sh]
----
spec:
  crds:
    externalCertManager: true
----
.. (Opcional) Adicione um nome `firstName` e sobrenome `lastName` do usuário associado à conta. Você pode executar esta etapa agora ou mais tarde dentro da IU.
.. (Opcional) altere o `storageClass` valor para outro recurso de storageClass do Trident, se necessário pela sua instalação.
.. (Opcional) se você quiser que o cluster seja gerenciado automaticamente pelo Astra Control Center após a instalação e já tiver <<substep_kubeconfig_secret,criou o segredo que contém o kubeconfig para este cluster>>, forneça o nome do segredo adicionando um novo campo a esse arquivo YAML chamado `astraKubeConfigSecret: "acc-kubeconfig-cred or custom secret name"`
.. Execute um dos seguintes passos:
+
*** *Outro controlador de entrada (ingressType:Generic)*: Esta é a ação padrão com o Astra Control Center. Depois que o Astra Control Center for implantado, você precisará configurar o controlador Ingress para expor o Astra Control Center com um URL.
+
A instalação padrão do Astra Control Center configura seu gateway (`service/traefik`) para ser do tipo `ClusterIP`. Essa instalação padrão requer que você configure adicionalmente um controlador/ingresso do Kubernetes para rotear o tráfego para ele. Se pretender utilizar uma entrada, link:../get-started/install_acc.html#set-up-ingress-for-load-balancing["Configure a entrada para o balanceamento de carga"]consulte .

*** *Balanceador de carga de serviço (ingressType:AccTraefik)*: Se você não quiser instalar um IngressController ou criar um recurso de entrada, defina `ingressType` como `AccTraefik`.
+
Isso implanta o gateway Astra Control Center `traefik` como um serviço do tipo Kubernetes LoadBalancer.

+
O Astra Control Center usa um serviço do tipo "LoadBalancer" (`svc/traefik` no namespace Astra Control Center) e exige que seja atribuído um endereço IP externo acessível. Se os balanceadores de carga forem permitidos em seu ambiente e você ainda não tiver um configurado, você poderá usar o MetalLB ou outro balanceador de carga de serviço externo para atribuir um endereço IP externo ao serviço. Na configuração do servidor DNS interno, você deve apontar o nome DNS escolhido para o Astra Control Center para o endereço IP com balanceamento de carga.

+

NOTE: Para obter detalhes sobre o tipo de serviço "LoadBalancer" e Ingress, link:../get-started/requirements.html["Requisitos"]consulte .





+
[listing, subs="+quotes"]
----
apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra
spec:
  *accountName: "Example"*
  astraVersion: "ASTRA_VERSION"
  *astraAddress: "astra.example.com"*
  *astraKubeConfigSecret: "acc-kubeconfig-cred or custom secret name"*
  *ingressType: "Generic"*
  autoSupport:
    *enrolled: true*
  *email: "[admin@example.com]"*
  *firstName: "SRE"*
  *lastName: "Admin"*
  imageRegistry:
    *name: "[your_registry_path]"*
    *secret: "astra-registry-cred"*
  *storageClass: "ontap-gold"*
----




== Instalação completa do operador e do Centro de Controle Astra

. Se você ainda não fez isso em uma etapa anterior, crie o `netapp-acc` namespace (ou personalizado):
+
[source, sh]
----
kubectl create ns [netapp-acc or custom namespace]
----
+
Resposta da amostra:

+
[listing]
----
namespace/netapp-acc created
----
. Instale o Astra Control Center no `netapp-acc` namespace (ou personalizado):
+
[source, sh]
----
kubectl apply -f astra_control_center_min.yaml -n [netapp-acc or custom namespace]
----
+
Resposta da amostra:

+
[listing]
----
astracontrolcenter.astra.netapp.io/astra created
----




== Verifique o status do sistema


NOTE: Se você preferir usar OpenShift, você pode usar comandos oc comparáveis para etapas de verificação.

. Verifique se todos os componentes do sistema foram instalados com êxito.
+
[source, sh]
----
kubectl get pods -n [netapp-acc or custom namespace]
----
+
Cada pod deve ter um status de `Running`. Pode levar alguns minutos até que os pods do sistema sejam implantados.

+
.Resposta da amostra
[%collapsible]
====
[listing, subs="+quotes"]
----
NAME                                     READY  STATUS   RESTARTS AGE
acc-helm-repo-6b44d68d94-d8m55           1/1    Running  0        13m
activity-78f99ddf8-hltct                 1/1    Running  0        10m
api-token-authentication-457nl           1/1    Running  0        9m28s
api-token-authentication-dgwsz           1/1    Running  0        9m28s
api-token-authentication-hmqqc           1/1    Running  0        9m28s
asup-75fd554dc6-m6qzh                    1/1    Running  0        9m38s
authentication-6779b4c85d-92gds          1/1    Running  0        8m11s
bucketservice-7cc767f8f8-lqwr8           1/1    Running  0        9m31s
certificates-549fd5d6cb-5kmd6            1/1    Running  0        9m56s
certificates-549fd5d6cb-bkjh9            1/1    Running  0        9m56s
cloud-extension-7bcb7948b-hn8h2          1/1    Running  0        10m
cloud-insights-service-56ccf86647-fgg69  1/1    Running  0        9m46s
composite-compute-677685b9bb-7vgsf       1/1    Running  0        10m
composite-volume-657d6c5585-dnq79        1/1    Running  0        9m49s
credentials-755fd867c8-vrlmt             1/1    Running  0        11m
entitlement-86495cdf5b-nwhh2             1/1    Running  2        10m
features-5684fb8b56-8d6s8                1/1    Running  0        10m
fluent-bit-ds-rhx7v                      1/1    Running  0        7m48s
fluent-bit-ds-rjms4                      1/1    Running  0        7m48s
fluent-bit-ds-zf5ph                      1/1    Running  0        7m48s
graphql-server-66d895f544-w6hjd          1/1    Running  0        3m29s
identity-744df448d5-rlcmm                1/1    Running  0        10m
influxdb2-0                              1/1    Running  0        13m
keycloak-operator-75c965cc54-z7csw       1/1    Running  0        8m16s
krakend-798d6df96f-9z2sk                 1/1    Running  0        3m26s
license-5fb7d75765-f8mjg                 1/1    Running  0        9m50s
login-ui-7d5b7df85d-l2s7s                1/1    Running  0        3m20s
loki-0                                   1/1    Running  0        13m
metrics-facade-599b9d7fcc-gtmgl          1/1    Running  0        9m40s
monitoring-operator-67cc74f844-cdplp     2/2    Running  0        8m11s
nats-0                                   1/1    Running  0        13m
nats-1                                   1/1    Running  0        13m
nats-2                                   1/1    Running  0        12m
nautilus-769f5b74cd-k5jxm                1/1    Running  0        9m42s
nautilus-769f5b74cd-kd9gd                1/1    Running  0        8m59s
openapi-84f6ccd8ff-76kvp                 1/1    Running  0        9m34s
packages-6f59fc67dc-4g2f5                1/1    Running  0        9m52s
polaris-consul-consul-server-0           1/1    Running  0        13m
polaris-consul-consul-server-1           1/1    Running  0        13m
polaris-consul-consul-server-2           1/1    Running  0        13m
polaris-keycloak-0                       1/1    Running  0        8m7s
polaris-keycloak-1                       1/1    Running  0        5m49s
polaris-keycloak-2                       1/1    Running  0        5m15s
polaris-keycloak-db-0                    1/1    Running  0        8m6s
polaris-keycloak-db-1                    1/1    Running  0        5m49s
polaris-keycloak-db-2                    1/1    Running  0        4m57s
polaris-mongodb-0                        2/2    Running  0        13m
polaris-mongodb-1                        2/2    Running  0        12m
polaris-mongodb-2                        2/2    Running  0        12m
polaris-ui-565f56bf7b-zwr8b              1/1    Running  0        3m19s
polaris-vault-0                          1/1    Running  0        13m
polaris-vault-1                          1/1    Running  0        13m
polaris-vault-2                          1/1    Running  0        13m
public-metrics-6d86d66444-2wbzl          1/1    Running  0        9m30s
storage-backend-metrics-77c5d98dcd-dbhg5 1/1    Running  0        9m44s
storage-provider-78c885f57c-6zcv4        1/1    Running  0        9m36s
telegraf-ds-2l2m9                        1/1    Running  0        7m48s
telegraf-ds-qfzgh                        1/1    Running  0        7m48s
telegraf-ds-shrms                        1/1    Running  0        7m48s
telegraf-rs-bjpkt                        1/1    Running  0        7m48s
telemetry-service-6684696c64-qzfdf       1/1    Running  0        10m
tenancy-6596b6c54d-vmpsm                 1/1    Running  0        10m
traefik-7489dc59f9-6mnst                 1/1    Running  0        3m19s
traefik-7489dc59f9-xrkgg                 1/1    Running  0        3m4s
trident-svc-6c8dc458f5-jswcl             1/1    Running  0        10m
vault-controller-6b954f9b76-gz9nm        1/1    Running  0        11m
----
====
. (Opcional) para garantir que a instalação esteja concluída, você pode assistir os `acc-operator` logs usando o seguinte comando.
+
[source, sh]
----
kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f
----
+

NOTE: `accHost` o registro de cluster é uma das últimas operações e, se falhar, não causará falha na implantação. No caso de uma falha de Registro de cluster indicada nos logs, você pode tentar o Registro novamente por meio do fluxo de trabalho  ou da API de adicionar clusterlink:../get-started/setup_overview.html#add-cluster["Na IU"].

. Quando todos os pods estiverem em execução, verifique se a instalação foi bem-sucedida (`READY` é `True`) e obtenha a senha única que você usará quando fizer login no Astra Control Center:
+
[source, sh]
----
kubectl get AstraControlCenter -n netapp-acc
----
+
Resposta:

+
[listing]
----
NAME    UUID                                      VERSION     ADDRESS         READY
astra   ACC-9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f  22.08.1-26  10.111.111.111  True
----
+

IMPORTANT: Copie o valor UUID. A palavra-passe é `ACC-` seguida pelo valor UUID (`ACC-[UUID]`ou, neste exemplo, `ACC-9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f` ).





== Configure a entrada para o balanceamento de carga

Você pode configurar uma controladora de entrada de Kubernetes que gerencia o acesso externo a serviços, como balanceamento de carga em um cluster.

Este procedimento explica como configurar um controlador de entrada (`ingressType:Generic`). Essa é a ação padrão do Astra Control Center. Depois que o Astra Control Center for implantado, você precisará configurar o controlador Ingress para expor o Astra Control Center com um URL.


NOTE: Se não pretender configurar um controlador de entrada, pode configurar `ingressType:AccTraefik)`o . O Astra Control Center usa um serviço do tipo "LoadBalancer" (`svc/traefik` no namespace Astra Control Center) e exige que seja atribuído um endereço IP externo acessível. Se os balanceadores de carga forem permitidos em seu ambiente e você ainda não tiver um configurado, você poderá usar o MetalLB ou outro balanceador de carga de serviço externo para atribuir um endereço IP externo ao serviço. Na configuração do servidor DNS interno, você deve apontar o nome DNS escolhido para o Astra Control Center para o endereço IP com balanceamento de carga. Para obter detalhes sobre o tipo de serviço "LoadBalancer" e Ingress, link:../get-started/requirements.html["Requisitos"]consulte .

Os passos diferem consoante o tipo de controlador de entrada que utiliza:

* Entrada de Istio
* Controlador de entrada nginx
* Controlador de entrada OpenShift


.O que você vai precisar
* O necessário https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/["controlador de entrada"] já deve ser implantado.
* O https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class["classe de entrada"] correspondente ao controlador de entrada já deve ser criado.
* Você está usando versões do Kubernetes entre o v1,19 e o v1,22, inclusive.


.Etapas para a entrada do Istio
. Configurar a entrada do Istio.
+

NOTE: Este procedimento pressupõe que o Istio é implantado usando o perfil de configuração "padrão". 

. Reúna ou crie o certificado e o arquivo de chave privada desejados para o Ingress Gateway.
+
Você pode usar um certificado assinado pela CA ou autoassinado. O nome comum deve ser o  endereço Astra (FQDN).

+
Exemplo de comando: 

+
[source, sh]
----
openssl req -x509 -nodes -days 365 -newkey rsa:2048 
-keyout tls.key -out tls.crt
----
. Crie um segredo `tls secret name`  do tipo `kubernetes.io/tls` para uma chave privada TLS e um certificado,  `istio-system namespace` conforme descrito em  segredos TLS.
+
Exemplo de comando: 

+
[source, sh]
----
kubectl create secret tls [tls secret name] 
--key="tls.key"
--cert="tls.crt" -n istio-system
----
+

TIP: O nome do segredo deve corresponder ao `spec.tls.secretName` fornecido no `istio-ingress.yaml` arquivo.

. Implante um recurso de entrada no `netapp-acc`  namespace (ou nome personalizado) usando o v1beta1 (obsoleto na versão do Kubernetes menor que ou 1,22) ou   o tipo de recurso v1 para um esquema obsoleto ou novo:
+
Saída:

+
[listing]
----
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: istio-system
spec:
  ingressClassName: istio
  tls:
  - hosts:
    - <ACC addess>
    secretName: [tls secret name]
  rules:
  - host: [ACC addess]
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: traefik
          servicePort: 80
----
+
Para o novo esquema v1, siga esta amostra:

+
[source, sh]
----
kubectl apply -f istio-Ingress.yaml
----
+
Saída:

+
[listing]
----
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: istio-system
spec:
  ingressClassName: istio
  tls:
  - hosts:
    - <ACC addess>
    secretName: [tls secret name]
  rules:
  - host: [ACC addess]
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik
            port:
              number: 80
----
. Implante o Astra Control Center como de costume.
. Verifique o estado da entrada:
+
[source, sh]
----
kubectl get ingress -n netapp-acc
----
+
Resposta:

+
[listing]
----
NAME    CLASS HOSTS             ADDRESS         PORTS   AGE
ingress istio astra.example.com 172.16.103.248  80, 443 1h
----


.Etapas para o controlador nginx Ingress
. Crie um segredo do tipo[`kubernetes.io/tls`] para uma chave privada TLS e um certificado no `netapp-acc` namespace (ou nome personalizado), conforme descrito em https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets["Segredos TLS"].
. Implante um recurso de entrada no `netapp-acc` namespace (ou nome personalizado) usando o `v1beta1` tipo de recurso (obsoleto na versão do Kubernetes menor que ou 1,22) ou `v1` para um esquema obsoleto ou novo:
+
.. Para um `v1beta1` esquema obsoleto, siga esta amostra:
+
[source, yaml]
----
apiVersion: extensions/v1beta1
Kind: IngressClass
metadata:
  name: ingress-acc
  namespace: [netapp-acc or custom namespace]
  annotations:
    kubernetes.io/ingress.class: [class name for nginx controller]
spec:
  tls:
  - hosts:
    - <ACC address>
    secretName: [tls secret name]
  rules:
  - host: [ACC address]
    http:
      paths:
      - backend:
        serviceName: traefik
        servicePort: 80
        pathType: ImplementationSpecific
----
.. Para o `v1` novo esquema, siga esta amostra:
+
[source, yaml]
----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netapp-acc-ingress
  namespace: [netapp-acc or custom namespace]
spec:
  ingressClassName: [class name for nginx controller]
  tls:
  - hosts:
    - <ACC address>
    secretName: [tls secret name]
  rules:
  - host: <ACC addess>
    http:
      paths:
        - path:
          backend:
            service:
              name: traefik
              port:
                number: 80
          pathType: ImplementationSpecific
----




.Passos para o controlador OpenShift Ingress
. Procure seu certificado e prepare os arquivos de chave, certificado e CA para uso pela rota OpenShift.
. Crie a rota OpenShift:
+
[source, sh]
----
oc create route edge --service=traefik
--port=web -n [netapp-acc or custom namespace]
--insecure-policy=Redirect --hostname=<ACC address>
--cert=cert.pem --key=key.pem
----




== Faça login na IU do Astra Control Center

Depois de instalar o Astra Control Center, você alterará a senha do administrador padrão e fará login no painel da IU do Astra Control Center.

.Passos
. Em um navegador, insira o FQDN usado no no `astraAddress`  `astra_control_center_min.yaml`CR quando <<Instale o Astra Control Center,Você instalou o Astra Control Center>>.
. Aceite os certificados autoassinados quando solicitado.
+

NOTE: Você pode criar um certificado personalizado após o login.

. Na página de login do Astra Control Center, insira o valor usado `email` no `astra_control_center_min.yaml` CR quando <<Instale o Astra Control Center,Você instalou o Astra Control Center>>, seguido da senha única (`ACC-[UUID]`).
+

NOTE: Se você digitar uma senha incorreta três vezes, a conta de administrador será bloqueada por 15 minutos.

. Selecione *Login*.
. Altere a senha quando solicitado.
+

NOTE: Se este for o seu primeiro login e você esquecer a senha e nenhuma outra conta de usuário administrativo ainda tiver sido criada, entre em Contato com o suporte da NetApp para obter assistência de recuperação de senha.

. (Opcional) Remova o certificado TLS autoassinado existente e substitua-o por um link:../get-started/add-custom-tls-certificate.html["Certificado TLS personalizado assinado por uma autoridade de certificação (CA)"].




== Solucionar problemas da instalação

Se algum dos serviços estiver `Error` no estado, pode inspecionar os registos. Procure códigos de resposta da API na faixa 400 a 500. Eles indicam o lugar onde uma falha aconteceu.

.Passos
. Para inspecionar os logs do operador do Centro de Controle Astra, digite o seguinte:
+
[source, sh]
----
kubectl logs --follow -n netapp-acc-operator $(kubectl get pods -n netapp-acc-operator -o name) -c manager
----




== O que vem a seguir

Conclua a implantação executando link:setup_overview.html["tarefas de configuração"]o .
